services:
  setup:
    image: busybox:1.37.0-musl
    command: chown -R 1000:1000 /workdir
    volumes:
      - poky:/workdir

  samba:
    image: crops/samba
    ports:
      - 445:445
    volumes:
      - poky:/workdir
    depends_on:
      setup:
        condition: service_completed_successfully

  poky:
    image: crops/poky
    volumes:
      - poky:/workdir
    depends_on:
      setup:
        condition: service_completed_successfully

volumes:
  poky:

