---
- name: "Setup home cloud"
  hosts: "master"
  vars_files:
    - "vars/main.yml"
    - "vars/{{ env }}.yml"
  roles:
    - role: "postgresql"
      postgresql_version: "12.3.1"
      postgresql_namespace: "{{ homecloud_namespace }}"
      postgresql_admin_password: "{{ postgresql.root_password }}"
      postgresql_volume_size: "{{ postgresql.volume_size }}"
